### PR TITLE
Updated R source code.

### PR DESCRIPTION
**Pull request by gavincyi**
R source code is updated. Analysis will be updated soon.

### CODE REVIEW

**Comment by gavincyi** [comment]
Added workflow document (~/Rmd/workflow.html)

**Comment by gavincyi** [comment]
Added data cleaning documentation.

**Comment by joshuaNewman10** [comment]
Hey this is fantastic work! I really love how well you documented your workflow, it makes it very easy to follow. Ill try to make a similar document so I can follow your workflow style. The only comment I have is that could you add the testing/training csv data to the gitignore file so we aren't uploading those large files to GitHub? Ill try to make sure I do the same

**Comment by gavincyi** [comment]
Fixed untracked files.

**Pull request merged**
